인프라: 네트워크 구조 설계
mash-up-kr/SeeYouAgain_iOS pull request #11
Opened 2023-05-04 06:32 UTC by klmyoungyun

## Task

[네트워크 레이어 추가]()

## 참고

2023-05-04 09:02 UTC, GREENOVER requested changes
고생 많았습니다!!🎉🎉🎉
너무 잘해주셔서 사실 Request Changes 될 이유는 로직적인 부분이나 구조에서 크게 없고
조금 더 코드 컨벤션 및 디테일한 부분들이 보완될 수 있을것 같고 시간이 아직 많기에 Request 드렸어요🙋🏻
코멘트 천천히 보시면서 다른 의견이나 더 나은 방향이 있으면 같이 공유해봐요🕺🏻

2023-05-07 03:22 UTC, AhnSangHee requested changes
고생하셨습니다아아아~~~👍👍👍

2023-05-07 03:22 UTC, AhnSangHee commented on Projects/Core/Services/_Foundation/TargetType.swift
> +
요기도 공백을 없애는게 낫지 않을까용?!

2023-05-07 03:22 UTC, AhnSangHee commented on Projects/Core/Models/Network/User/UserDTO.swift
>  import UIKit
꼭 필요한 import인가용??!!

2023-05-07 03:22 UTC, AhnSangHee commented on Projects/Core/Services/_Foundation/TargetType.swift
> +
공백은 없애는 게 좋을 것 같아요~!

2023-05-07 03:27 UTC, lina0322 commented on Projects/Core/Models/Network/User/UserDTO.swift
>  import UIKit
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ자연스럽다 상희

2023-05-07 03:27 UTC, lina0322 commented on Projects/Core/Services/_Foundation/TargetType.swift
> +
5월 3일은 영균's 공백데이라서 그랬나봐요

2023-05-07 23:55 UTC, GREENOVER commented on Projects/Core/Services/_Foundation/NetworkEventLogger.swift
> +    print("=============== 📍 Network Request Log 📍 ===============\n")
근데 요런 그냥 문자열 자체를 debugPrint로 하는것하고 print로 하는것하고 로깅 시 차이가 더 있나요!?

예를들어 해당 문자열을 debugPrint로 찍게되면,
```
"=============== 📍 Network Request Log 📍 ===============\n"
```
으로 ""로 타입까지 알려주면서 감싸지는데,
print로 출력하게 되면
```
=============== 📍 Network Request Log 📍 ===============
```
으로 나타나기에 즉 해당 출력문은 어떤 타입인지까지 디버깅할 필요가 없이 아래 로깅 정보들에 대한 시작점임을 알리기에 print로 출력하는게 조금 더 깔끔하지 않나 싶어서요..!

2023-05-08 02:49 UTC, lina0322 commented on Projects/Core/Services/_Foundation/NetworkEventLogger.swift
> +    print("=============== 📍 Network Request Log 📍 ===============\n")
오, 그런 부분도 고려할 수 있을 것 같습니다!
다만 제 관점은 print는 생각보다 무거운 작업이고, 사용자들이 사용하는 실서비스 앱에서 이런 불필요한 작업이 굳이 동작할 필요가 있을까 하는게 의문입니다.🤔

그리고 지금 말씀하신 것 처럼 시작점을 알리는 부분이고, 타입을 확인하기 위해서 사용하고 있는 작업은 아니지만, “”로 감싸져서 출력되는 부분이 좀 더 깔끔하지 않다는 이유로 print를 사용할 필요까진 없는 것 같아요! 

사실상 로그를 확인하기 위함이라면 os_log가 정석이라는 생각도 드는데욯ㅎㅎ 결론적으로 저는 개인적으로 debugPrint가 간편해서 사용하고 있습니당🫣

다른분들도 의견있으면 편하게 말씀해주세용~

2023-05-08 03:35 UTC, GREENOVER commented on Projects/Core/Services/_Foundation/NetworkEventLogger.swift
> +    print("=============== 📍 Network Request Log 📍 ===============\n")
오 그럴수 있겠네요!
print의 취지는 아닌것 같아 리나 코멘트가 더 적절할것 같아요👍

2023-05-08 04:53 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Task.swift
> +  case requestParameters(parameters: [String: Any], encoding: ParameterEncoding)
Task에 Encodable한 타입을 처리 분기를 추가하겠습니다~!

2023-05-08 04:54 UTC, klmyoungyun commented on Projects/Core/Services/User/UserService.swift
> +        .request(UserAPI.getUser, type: [UserDTO].self)
서비스에서 발생한 에러는 ErrorFactory인 SeeYouAgainError 프로토콜을 채택한 ServiceError를 만들어 처리해야할 것 같습니다!

2023-05-08 04:55 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/NetworkEventLogger.swift
> +
작성한 스타일 가이드대로 전부 삭제하겠습니다~!~!

2023-05-08 04:55 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/NetworkEventLogger.swift
> +    }
찬성입니다~!

2023-05-08 04:55 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Provider.swift
> +extension Provider {
반영하겠습니다!

2023-05-08 04:56 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Provider.swift
> +              let error = ProviderError(code: .failedDecode, userInfo: ["target" : target], response: response)
스타일 가이드대로 수정했습니당

2023-05-08 04:56 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/ResponseDTO.swift
> +      case message
어라라... 바로 수정했습니다😅

2023-05-08 04:59 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Session.swift
> +    configuration.timeoutIntervalForResource = 10
명확한 기준은 없습니다. 기본값이 60초인데 보통 통신이 10초안에 끝난다고 생각해 10초로 잡았습니다. 기준 값 선정에 참고할 자료나 의견있으신가요?!🙇🏻‍♂️

2023-05-08 05:00 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/TargetType.swift
> +
네!

2023-05-08 05:01 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Provider.swift
> +  private let AFSession: Alamofire.Session
수정했습니다!~!

2023-05-08 05:07 UTC, klmyoungyun commented on Projects/Core/Models/Network/User/UserDTO.swift
> +  }
네네ㅔ 위치가 잘못되서 멤버와이즈 이니셜라이저 사용하는 방식으로 변경하겠습니다
```swift
public extension UserDTO {
  static let stub = UserDTO.init(id: 1, name: "Leanne Graham")
}
```

2023-05-08 05:08 UTC, klmyoungyun commented on Projects/Core/Services/User/UserAPI.swift
> +      return .requestParameters(parameters: ["id": "1"], encoding: URLEncoding.queryString)
좋아요! 반영하겠습니다~!

2023-05-08 05:09 UTC, klmyoungyun commented on Projects/Core/Services/User/UserAPI.swift
> +  public var sampleData: Data {
TargetType 프로토콜이 public이라 그렇습니당

2023-05-08 05:10 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/TargetType.swift
> +
ㅠㅠㅠ🫠

2023-05-08 05:27 UTC, GREENOVER commented on Projects/Core/Services/_Foundation/Session.swift
> +    configuration.timeoutIntervalForResource = 10
저는 기본값인 60초를 기준으로 가져가긴 합니다..!
60초를 기본값으로 라이브러리등에서도 가져가는 이유에 대해 명확하게 왜 딱 60초인지 저도 확실하게 답은 모르겠찌만 ㅠ
10초안에 보통 끝나긴 하지만 네트워크가 느린 지역이나 환경이 있다면 10초는 조금 짧을것 같아요. (엘베 등이 될수도..!?)
그런걸 고려해서 아마 기본적으로 60초가 평균적으로 확률이 높기에 가져가는것이지 않을까하는 추측이 있어요..!
더 명확한 이유가 있다면 같이 찾아봐도 좋을것 같습니다🙋🏻

2023-05-08 05:42 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Session.swift
> +    configuration.timeoutIntervalForResource = 10
네트워크가 느린 지역을 생각하지 못한 것 같습니다.😅 10초는 짧을 것 같아요. 
일단 디폴트 값으로 사용하고 추후에 명확한 기준이 정해지면 변경해도 늦지 않을 것 같습니다😀
감사합니다~!

2023-05-08 06:15 UTC, klmyoungyun commented on Projects/Core/Services/User/UserAPI.swift
> +    }
네엥!

2023-05-08 06:17 UTC, klmyoungyun commented on Projects/Core/Services/_Foundation/Task.swift
> +import Foundation
`case requestCustomJSONEncodable(Encodable, encoder: JSONEncoder)`로 인해.. 이제 필요합니다..

2023-05-08 06:24 UTC, GREENOVER approved these changes
수고하셨습니다! 리팩토링 된것 잘 확인했어요👍👍👍
고생 많았습니다🎉🎉🎉

2023-05-09 02:24 UTC, lina0322 approved these changes

2023-05-09 08:54 UTC, GREENOVER commented
@klmyoungyun 머지 가즈아~

2023-05-09 12:37 UTC, merged