기능: 커스텀 탭뷰 구현
mash-up-kr/SeeYouAgain_iOS pull request #28
Opened 2023-06-06 14:15 UTC by AhnSangHee

## Task

[커스텀 탭뷰 구현]()

## 참고

2023-06-07 00:14 UTC, GREENOVER requested changes
고생하셨습니다!!
너무 커스텀하게 잘 만들어주셔서 아주 사용하기 좋겠어요ㅎㅎ
현재 나온 DS와 살짝 커스텀 탭바가 다르게 생긴 부분이 있어 피그마가 현재 업데이트가 안된건지 어떤지 확인 부탁드립니다🙏🏻

나머지는 정말 궁금한 부분들 여쭤봤습니다~!

2023-06-07 00:14 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarItem.swift
> +  public var icon: Image {
defaultIcon은 어떠신가요?

2023-06-07 00:14 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
> +import DesignSystem
필요한가요~?!

2023-06-07 00:14 UTC, GREENOVER requested changes
고생하셨습니다!!
너무 커스텀하게 잘 만들어주셔서 아주 사용하기 좋겠어요ㅎㅎ
현재 나온 DS와 살짝 커스텀 탭바가 다르게 생긴 부분이 있어 피그마가 현재 업데이트가 안된건지 어떤지 확인 부탁드립니다🙏🏻

나머지는 정말 궁금한 부분들 여쭤봤습니다~!

2023-06-07 00:33 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarContainerView.swift
> +  let content: Content
앗 그러네욥 수정하겠습니다😀

2023-06-07 00:35 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +    )
`.padding(.horizontal, 24)`로 표현하는 게 더 좋은 것 같아요! 수정하겠습니다ㅎㅎ

2023-06-07 00:36 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
> +import DesignSystem
앗 다른 테스트하다가 추가된 것 같습니다😅 불필요해서 제거했습니다!!!

2023-06-07 00:38 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarItem.swift
> +  public var icon: Image {
defaultIcon도 좋습니다! 더 명확히 나타내기 위해 default를 추가하는게 좋겠네요ㅎㅎ

2023-06-07 00:43 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarContainerView.swift
> +public struct ShortsTabBarContainerView<Content: View>: View {
동의합니다~! internal로 변경하였습니다😀

2023-06-07 00:52 UTC, AhnSangHee commented on Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorCore.swift
> +        embedInNavigationView: true
false로 할 경우, 내비게이션바가 추가되지 않아서
<img src = "https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/95578975/93c1c745-e903-4667-8941-d100a592cae7" width="40%" height="40%">

위 사진과 같이 safeArea를 침범해서 텍스트가 표현되어서 모든 곳에 true를 추가하게 되었습니다!

2023-06-07 05:41 UTC, lina0322 approved these changes
고생하셔쑴다 차누쓰가 말한거 수정하시면 될고같네여 체고에여

2023-06-07 05:41 UTC, lina0322 commented on Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordView.swift
> +      HStack {
지나가던 사람인데요. 사진 크기 width를 추가하면 작게 할 수 있숨다. 알거같은데 그냥 알려주고싶다. 뭐라도 한마디 적고싶다^_^

ex `<img width="320" src="https://github.com/adfalkdfaldj">`

<img width="320" alt="스크린샷 2023-05-24 16 25 32" src="https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/49546979/b5229f6d-9b1b-4374-ae3a-05afd6b78ca1">

2023-06-08 01:38 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +          Color.white.ignoresSafeArea(edges: .bottom)
`ignoresSafeArea(edges: .bottom)`는 필요하지 않네요😅 제거했습니다!
그리고 지금 DS에 배경색이 정의되어있지 않아서 일단 임시로 제일 비슷한 색상인 Grey20으로 정의해두었고, border도 추가했습니다!

2023-06-08 10:36 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +public struct ShortsTabBarView: View {
일단은 Scene에 두되 internal로 유지하고, 후에 DS가 완전히 정리된다면 DS 영역으로 빼는 것도 다시 고려해보도록 하겠습니다!

2023-06-08 15:26 UTC, AhnSangHee commented on Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordView.swift
> +      HStack {
배경색은 단지 구분을 위해 추가를 했었습니다! 추가적으로 지금처럼 HStack이 VStack 상위에 존재하게 되면 추후 뷰 구성 시 어색할 것 같네요!!!! 코멘트 남겨주신 것처럼 수정했습니다!😀

2023-06-08 15:53 UTC, AhnSangHee commented on Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
> +    VStack(spacing: 0) {
지금 상황에서는 필요한 것이 아닌데 추가했네요🥲 필요하지 않은 다른 뷰들에서도 모두 제거했습니다!!!

2023-06-08 22:25 UTC, GREENOVER approved these changes
수고많으셨습니다!!
동작과 코드 이상무👍👍👍
마이너한 코멘트만 남겼는데 요건 다음 피쳐 진행하면서 같이 반영되면 좋을것 같아요🎉

2023-06-08 22:25 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +  public var body: some View {
public하지 않아도 될것 같아요🙋🏻

2023-06-08 22:25 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +          .font(DesignSystemFontFamily.Pretendard.bold._14)
단순히 `.font(.b14)`로 폰트는 표현할 수 있습니다👍

2023-06-08 22:25 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +    .scaleEffect(1)
`scaleEffect(1)`이 어떤 영향을 미치나요?🤔
현재 뷰에서는 불필요한 코드 같긴합니다🙋🏻

2023-06-08 22:55 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
> +    .scaleEffect(1)
애니메이션이 어색한 부분을 해결하기 위해 `scaleEffect(1)`을 추가했고, 애니메이션이 조금 더 자연스럽습니다!

추가 전|추가 후
---|---
![nonanimation](https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/95578975/8d4cb5d2-a98e-4b4e-8c6a-8b86dac8a188)|![animation](https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/95578975/7c0e36d2-af84-444c-b597-fcbaf99b40e8)

2023-06-08 22:58 UTC, merged