기능: 메인 카테고리 뱃지 및 바텀 시트 구현
mash-up-kr/SeeYouAgain_iOS pull request #31
Opened 2023-06-08 17:10 UTC by klmyoungyun

## Task

[메인 키워드 뱃지 및 바텀 시트 구현](#29)

## 참고
- `BlurEffectModifier`를 추가했습니다. background blur 효과를 주기위해 아래처럼 사용할 수 있습니다. (근데 맞는지 모르겠습니다요)
  ```swift
  .background(Color.white.opacity(0.8).blurEffect())
  ```

- 탭바 뷰에서 바텀 시트를 띄웠습니다. 나중에 바텀 시트를 띄울 일이 있으면 `BottomSheetCore`에 추가하여 사용하면 됩니다. 카테고리 변경 로직은 아래와 같습니다.
   1. `TabBarCore`에서 메인에서 발생한 액션을 캐치합니다.
   		```swift
		case let .main(.routeAction(_, action: .main(.openBottomSheet(category)))):
			state.bottomSheet.categories = category
			state.bottomSheet.categoryBottomSheetIsPresented = true
    	return .none
   		```
   2. `BottomSheetCore`에서 카테고리 상태 변경을 처리합니다.
   3. 바텀 시트 닫는 액션을 수행합니다.
       1. `BottomSheetCore`에서 바텀 시트의 `isPresented`를 변경합니다.
        	```swift
			case .closeCategoryBottomSheet:
				state.categoryBottomSheetIsPresented = false
				return .none
			```
      2. 만약 변경이 있다면 `TabBarCore`에서 변경된 카테고리를 메인에 전달합니다.
    		```swift
			case .bottomSheet(.categoryUpdateButtonTapped):
				let category = state.bottomSheet.categories
				return Effect.concatenate([
					Effect(value: .bottomSheet(.closeCategoryBottomSheet)),
					Effect(value: .main(.routeAction(0, action: .main(.updateCategories(category)))))
				])
	  		```
아래는 실행화면입니다.
![Simulator Screen Recording - iPhone 14 Pro - 2023-06-09 at 01 41 08](https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/48887389/6fafb2df-02bd-4427-8770-927bdad0ea19)

2023-06-08 17:17 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
> +      state.bottomSheet.categoryBottomSheetIsPresented = true
타고 들어가서 상태를 변경하는 것보다 아래처럼 `BottomSheetCore`에 액션을 추가해 카테고리를 변경하는게 더 좋을까요? ㅠ.ㅠ
```swift 
return Effect.concatenate([
  Effect(value: .bottomSheet(.copyCategories(category)),
  Effect(value: .bottomSheet(.openCategoryBottomSheet)
])
```

2023-06-08 22:37 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
> +      state.bottomSheet.categoryBottomSheetIsPresented = true
시트코어 액션에서 이뤄지는거면 더 관심사가 맞을것 같긴해요🙋🏻
사실 메인 코어에서 openBottomSheet를 눌렸을때 상위에서 직접 상태값을 컨트롤하는것보다 그런 상태값들은 자기네들 코어에서 해주는게 더 적절하긴 합니다!
선택이긴 하지만 영균이가 더 의미있다고 생각하는걸로 하면 될듯

2023-06-08 22:42 UTC, GREENOVER commented
@klmyoungyun 
현재 Scene 프로젝트 파일을 보면 
```
.make(
      name: "TabBar",
      product: .staticLibrary,
      bundleId: "com.mashup.seeYouAgain.tabBar.tabBar",
      sources: ["TabBarScene/TabBar/**"],
```
소스 루트가 TabBar 폴더로 한정되어 있어서 BottomSheet 폴더가 씹혀요🥲
BottomSheet 폴더 위치 조정 혹은 Project 파일 수정을 부탁드립니다🙏🏻

2023-06-08 23:45 UTC, GREENOVER requested changes
@klmyoungyun 
수고 많으셨습니다👍👍👍
수정되어야 하거나 의견 나눌 부분들 리뷰 남겼어요!
아..! 그리고 앞서 코멘트 남긴것처럼 우선적으로 빌드가 되려면 프로젝트 파일 변경이 되어야하고 AppCoordinatorCore에서도 
```
case .routeAction(_, action: .splash(.viewDidLoad)):
        state.routes = [
          .root(
            .tabBar(.init(hotKeyword: .init(), main: .init(), myPage: .init(), bottomSheet: .init())),
            embedInNavigationView: true
          )
        ]
``` 
요 부분 bottomSheet 이닛을 해줘야합니다!

다른분들도 바로 받아서 하면 빌드가 안되실거기 때문에 ㅠ
로컬에서 작업하더라구 파일들이 많이 변경 추가되었다면 마무리 푸쉬전 grunt pr로 다시 플젝 셋팅하고 빌드 테스트 부탁드립니다🙏🏻

아..! 그리구 뷰 시점 차이인지 아주아주 간혹 아래와 같이 메인뷰에서 카테고리 stub이 안들어갈때가 있드라구요.
혹시 발견하시면 확인 부탁드립니다~!
<img width="320" src="https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/72292617/87e9cf39-11e7-4bf3-b5c2-f4077757171d">

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
> +  }
이미 rawValue를 사용하고 있어보이는데 하나만 가져가도 될것 같아요🤔
또한 제가 Common에 동일한 네이밍으로 CategoryType을 만든것이 있는데 제 PR과 머지되면 거기서 보완해서 공통적으로 사용하는게 좋을것 같습니다🙋🏻
(아이콘이나 사이즈등 필요한 computed property를 거기서 추가하면 좋을듯!)

2023-06-08 23:45 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/Button/CategoryDetailButton.swift
> +public struct CategoryDetailButton: View {
요런친구들은 굳이 DS 영역에 있을 필요는 크게 없어보이는데 어떻게 생각하시나요!?🙋🏻
이유는 너무 고정적으로 딱 한 디테일 뱃지를 보여주는 뷰이기에 다른곳에서는 사용되지 않을것 같아 DS에 담긴다면 DS를 들고 있는 모듈도 작게나마 이 친구를 들고 있게 된다고 보여서요🤔
해당 뷰에서만 쓰이는 간단한 뷰들은 DS보다 내부 뷰로 구성하면 어떨가 싶습니다..!

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/Category/CategoriesView.swift
> +  }
LGTM👍

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/Category/CategoriesView.swift
> +                // TODO: filter news cards.
아주아주 나중에 해도 되긴하는데 뱃지가 스크롤되어 가려진 경우에 뱃지를 눌렀을때 자동 오프셋 포지셔닝 조정을 해주면 사용자 경험에 좋을듯! 피그마에도 없고 한데 그냥 일반적으로는 처리를 그렇게 하긴해서..!

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  case setIsLoading(Bool)
Inner 액션에 대해서는 _를 붙이는건 어떤가요?🙋🏻
정말 스타일의 차이긴한데 코어에 액션들이 많아질수록 이 친구들이 유저/외부 액션인지 아니면 내부 상태 변경이나 서비스 로직의 액션인지 네이밍만으로는 헷갈릴때가 많아 Inner를 구분해주는 용도로 저는 붙여주긴 합니다.

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  var userService: UserService = .live
여기서 값을 바로 넣어주는것보다 최상단에서 주입받아서 사용하는것이 좋습니다..!

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
> +public typealias Category = Models.Category
필요한 코드인가요!?🙋🏻

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
> +              }
연애/스포츠가 동일한 뷰로 그려지는데 피그마와 비슷하게 다른 뷰를 보여줘야함과 동시에 선택이 되지 않도록 처리되어야 할것 같습니다🙋🏻

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +  case .closeCategoryBottomSheet:
액션 정의 순서와 동일하게 toggleCategory 액션보다 위에 올라와야 할것 같아요🙋🏻

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +  case toggleCategory(Category)
먼저 사용자가 해당 카테고리를 탭하고 선택된 카테고리가 토글되는것은 내부 로직으로 보입니다.
그렇기에 추후 확장성을 고려한다면 이 흐름은 어떤가요?
```
  case categoryTapped(Category)
  case _toggleCategory(Category)
  (이거까지는 선택..) case _setCategory(Category)
```
카테고리를 탭하면 toggleCategory 액션을 호출하여 그 내에서 카테고리를 토글하고 해당 [Category] 값을 setCategory에 넘겨줍니다.
해당 setCategory에서는 단순하게 받아온 값을 state.categories로 value set해줍니다.
결국 관심사를 다 쪼개서 액션을 만드는것인데 별거 아닌 작업에 이렇게 쪼개는게 귀찮고 더 오버 엔지니어링일 순 잇어보이지만 추후 더 많이 유용하긴 합니다.
액션을 해당하는 역할만 해주는것이 TCA를 사용하여 모듈의 관심사를 분리하고 조립하는것처럼 중요하다고 생각해요🙋🏻
현재는 카테고리가 탭되었을때 toggleCategory 액션을 발행하기에 추후 만약 카테고리가 탭되면 toggle외 토스트 메시지도 띄우는 등 추가 액션이 들어가면 toggleCategory 내에서 처리하거나 다른 로직을 부르기엔 이미 toggleCategory 액션의 역할을 지나치게 됩니다.

그렇기에 액션을 User / Inner Business / Inner Set State 등으로 확실히 구분짓는 명확한 이유입니다😃

2023-06-08 23:45 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +public struct BottomSheetState: Equatable {
카테고리에 대한 한정적인 바텀 시트 코어라고 보이는데 그렇다면 CategoryBottomSheet로 가는게 어떤가 싶습니다~!

2023-06-08 23:46 UTC, GREENOVER commented
@klmyoungyun 
추가로 현재 메인에 상희랑 공통사항들이 겹쳐서 반영되어서 컨플릭처리 부탁드려요..!

2023-06-09 01:05 UTC, klmyoungyun commented on Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
> +}
헉! 수정했습니다! https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/76fd335ce7742344a9852b6522f0cf8859da076c

2023-06-09 01:16 UTC, klmyoungyun commented on Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
> +}
음,, Header 부분도 `bottomArea`처럼 `headerArea`같이 제너릭으로 바꾸면 어떨까요?

2023-06-09 01:18 UTC, klmyoungyun commented on Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
> +  }
네네!! 일단 중복되어보이니 제거하겠습니당

2023-06-09 01:21 UTC, klmyoungyun commented on Projects/DesignSystem/Sources/Views/Button/CategoryBadgeButton.swift
> +        Text("\(name)")
수정완료! [f22d32d](https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/f22d32d69df9c8bab93d87bc0d86f22e63077333)

2023-06-09 01:25 UTC, klmyoungyun commented on Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
> +  }
적용완료🙌 https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/e79624fc7247d5f7dad8876775cac329215c4828

2023-06-09 01:41 UTC, lina0322 approved these changes
영규니 고생하네 화이팅 ㅎ_ㅎ

2023-06-09 01:41 UTC, lina0322 commented on Projects/DesignSystem/Sources/Views/Background/BlurEffect.swift
> +  var effect: UIVisualEffect?
UIVisualEffect 공부하느라 고생했숨당

2023-06-09 01:41 UTC, lina0322 commented on Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
> +}
나 궁금한게 찬우가 만든거랑 영균이가 만든거랑 따로따로써????

2023-06-09 01:41 UTC, lina0322 commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  case setIsLoading(Bool)
이거 몬가 신기한데, 궁금한게 원래 언더바 붙이는거 예전 C언어 스타일로 알고있는데, 아무래도 TCA를 쓰면서 이쪽이 다 public으로 설정되다보니 이렇게 구분하는곤가여?

2023-06-09 01:52 UTC, klmyoungyun commented on Projects/DesignSystem/Sources/Views/Button/CategoryDetailButton.swift
> +public struct CategoryDetailButton: View {
맞아여!!@ 옮기기 완료~! https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/f1c44d5f9e86df3f77abdde58bc0167b4a8008ef

2023-06-09 01:54 UTC, klmyoungyun commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  case setIsLoading(Bool)
👀👀

2023-06-09 02:04 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
> +public typealias Category = Models.Category
모델에 카테고리가 다른거에 가려져서 필요하다면 필요한데 위치가 잘못된 것 같습니다. 😅😅😅😅😅
Models 임포트 빼고 다른 위치로 옮기겠습니당

2023-06-09 02:06 UTC, klmyoungyun commented on Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
> +}
서로 작업하느라 두 개 생긴거같아요,, 머지하고 하나로 합칠 예정입니당🥹

2023-06-09 02:30 UTC, GREENOVER commented on Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
> +}
아주 좋아요!

2023-06-09 02:32 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  case setIsLoading(Bool)
네네 맞아여 ㅋㅋ 다 public해서 액션 자체가 그래서 나는 _로 좀 구분짓는 편인데 플젝 규모가 작으면 글케까진 필요없긴한데 우리가 우선 User부터 Inner까지 세부적으로 나눠가지고 리듀서에서 사용할때 그 나눠진 역할을 네이밍만보고 모호할때가 있어서 _를 붙여줌으로 좀 구분지을까했어요!
만약 이게 더 번거로울거 같으면 패쓰~ 해도됩니다~
자유로운 의견 ㄱㄱ

2023-06-09 03:53 UTC, AhnSangHee reviewed
애니메이션 작업이 굉장히 어려우셨을텐데 고생 많으셨습니당 😀😀😀

2023-06-09 03:53 UTC, AhnSangHee commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  case setIsLoading(Bool)
_ 붙이는거 좋은 것 같습니당~~~~!

2023-06-09 03:53 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +  public var categoryBottomSheetIsPresented: Bool = false
혹시
```suggestion
  public var isCategoryBottomSheetPresented: Bool = false
```
는 어떠신가요?!!

2023-06-09 04:23 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +  public var categoryBottomSheetIsPresented: Bool = false
BottomSheetState을 CategoryBottomSheetState로 변경하면 대상이 명확해지니 `isPresented`로 변경하면 어떤가요!~?

2023-06-09 04:27 UTC, AhnSangHee commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +  public var categoryBottomSheetIsPresented: Bool = false
아주 좋습니당!!!!!!!!!!!

2023-06-09 04:52 UTC, klmyoungyun commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  var userService: UserService = .live
맞습니다! 근데 사용하지 않는 코드라서 일단 지웠습니다..,,😅😅 괜찮을까요

2023-06-09 04:53 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
> +  case toggleCategory(Category)
관심사 분리 배워갑니다,,

2023-06-09 04:54 UTC, klmyoungyun commented on Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
> +}
수정했습니다~ https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/22c94b998222db3e37c1ae6a2802786d73a53f83

2023-06-09 04:57 UTC, GREENOVER commented on Projects/Features/Scene/MainScene/Main/MainCore.swift
> +  var userService: UserService = .live
네 좋아요! 나중에 필요할때 추가하면 딱좋을듯해요 ㅎㅎ

2023-06-09 07:50 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
> +      state.bottomSheet.categoryBottomSheetIsPresented = true
바텀 시트 코어로 변경했습니다.~ [링크](https://github.com/mash-up-kr/SeeYouAgain_iOS/blob/b7c72bffa1b1912f1a448d209072666c16770a5a/Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift#LL90C3-L94C8)

2023-06-09 07:51 UTC, klmyoungyun commented on Projects/DesignSystem/Sources/Views/Background/BlurEffect.swift
> +  var effect: UIVisualEffect?
감사합니당🫡🫡

2023-06-09 07:53 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
> +              }
처리했습니다. 일단 문자열로 체크하는데 머지되면 형이 만든 CategoryType으로 체크하는 방식으로 바꾸겠습니다.
https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/afccf55a0621c99d5f2cbc5dea8047db6ec84b62

2023-06-10 10:56 UTC, AhnSangHee approved these changes

2023-06-11 05:10 UTC, GREENOVER approved these changes
수고많았습니다!
두가지만 코멘트 남겼는데 이건 다음 작업 이어서 하시면서 반영되어도 될것 같아요🙌

2023-06-11 05:10 UTC, GREENOVER commented on Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
> +            .tabBar(.init(hotKeyword: .init(), main: .init(), myPage: .init(), categoryBottomSheet: .init())),
추후 요것도 개행해주면 좋을듯!

2023-06-11 05:10 UTC, GREENOVER commented on Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
> +private struct InActiveCategory: View {
inactive는 In-Active의 합성어라기보단 Inactive라고 하나의 형용사니 InactiveCategory가 맞지 않을까 생각합니다🙋🏻

2023-06-11 05:20 UTC, klmyoungyun commented on Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
> +private struct InActiveCategory: View {
[46f4b53](https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/46f4b53276826750e8825398a4b73061c8e616b0)
반영 완료!

2023-06-11 05:20 UTC, klmyoungyun commented on Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
> +            .tabBar(.init(hotKeyword: .init(), main: .init(), myPage: .init(), categoryBottomSheet: .init())),
[3272f75](https://github.com/mash-up-kr/SeeYouAgain_iOS/pull/31/commits/3272f7538db592be49677708fcc6ede41bee88df)
반영 완료!

2023-06-11 05:20 UTC, merged