기능: 오늘의 숏스 화면 구현
mash-up-kr/SeeYouAgain_iOS pull request #58
Opened 2023-06-23 02:36 UTC by AhnSangHee

## Task

[]()

## 참고

2023-06-23 04:39 UTC, GREENOVER requested changes
시간이 별로 없어서 메이저한거만 빠르게 봤어요!!

2023-06-23 04:39 UTC, GREENOVER commented on Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageCoordinatorCore.swift
> +            shortslistCount: 6,
합성어이니 shortsListCount는 어떠신가요?
혹시 6의 값은 어떻게 산정되는건가요~?

2023-06-23 04:39 UTC, GREENOVER commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
> +  ) {
인자 하나면 그냥 개행 없어도 될듯합니다~!

2023-06-23 04:39 UTC, GREENOVER commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
> +        ScrollView {
안에 담긴 뷰들을 내부 뷰들로 쪼개면 성능이 더 좋아질것 같아요~!

2023-06-23 04:39 UTC, GREENOVER commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
> +      }
요 사이 Spacer() 넣어보실래요?
(PR 코멘트에 대한 답변)

2023-06-23 04:44 UTC, AhnSangHee commented on Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageCoordinatorCore.swift
> +            shortslistCount: 6,
앗 놓쳤네요 shortsListCount로 변경했습니다! 6은 지금 목으로 넣어주는 데이터입니다!!!

2023-06-23 05:25 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
> +      }
넣어봤는데 똑같네요ㅜㅜ 한번 다시 천천히 살펴볼게요!!!!!

2023-06-23 07:56 UTC, klmyoungyun reviewed
누나 고생하셨습니다! 👏
전 코어의 로직을 위주로 체크해봤습니다!

2023-06-23 07:56 UTC, klmyoungyun commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsItemCore.swift
> +  case shortsItemSelectionChanged
언더바가 빠진 것 같아요!

2023-06-23 07:56 UTC, klmyoungyun commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
> +      return Effect(value: ._updateTimer)
1초에서 0초로 안 바뀌어요! 
`state.remainTimeString`을 바꾸지않고 `_updateTimer`을 호출해서 그런 것 같습니다.

![Simulator Screen Recording - iPhone 14 Pro Max - 2023-06-23 at 16 14 33](https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/48887389/921c3a5d-b050-404a-a2e3-c410e09d0bf2)

2023-06-23 07:56 UTC, klmyoungyun commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
> +      return Effect(value: ._updateTimer)
상태 설정하는 액션에서 다른 상태 설정 액션을 호출하니 해당 액션의 역할이 커진 느낌인데 
상태 설정 하는 액션은 딱 상태만 변경하게 하는 게 어떨까요!
```swift
    case let ._setCurrentTimeSeconds(currentTimeSeconds):
      state.currentTimeSeconds = currentTimeSeconds
      return .none
```
또한 해당 액션들은 _checkZeroTime 과정에서 호출되니 _checkZeroTime에 묶을 수 있지 않을까요!?

2023-06-23 23:48 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
> +      return Effect(value: ._updateTimer)
앗 놓쳤네요!!!! 😅 수정했습니다! 참고로 `_checkZeroTime`은 자정일 때 데이터를 초기화해주는 역할을 하고 있어서 `_updateZeroTIme`으로 네이밍 수정했습니다!

```swift
case ._decreaseRemainTime:
   state.remainTime -= 1
   return Effect(value: ._setRemainTimeString(state.remainTime))

case let ._setRemainTimeString(time):
   state.remainTimeString = remainTimeToString(time: time)
      
   if time == 0 {
      return Effect(value: ._updateZeroTime)
   }
   return .none
```

2023-06-24 00:28 UTC, GREENOVER commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
> +      }
해결되셨나요?
저기가 아니고 요쪽 컨트롤 해줘도 될거 같은데
`TodayShortsItemView` 코드내
```
HStack(spacing: 0) {
  if viewStore.state.isInEditMode {
    Toggle("", isOn: viewStore.binding(get: \.isSelected, send: .shortsItemSelectionChanged))
      .labelsHidden()
      .toggleStyle(ShortsToggleStyle())
      .frame(width: 24, height: 24)
    
    Spacer()
      .frame(width: 16)
  }
  
 // 스페이서 추가
  Spacer()
  
  TodayShortsCardView(
    store: store.scope(
      state: \TodayShortsItemState.cardState,
      action: TodayShortsItemAction.cardAction
    )
  )
}
```
일단 앞쪽 프레임은 조정해야겠지만 뒤는 고정되있습니다~!

2023-06-24 03:25 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
> +      }
찬우오빠가 알려주신대로 TodayShortsCardView의 뷰 사이즈가 모호해서 생기는 문제였습니당😭😭😭
TodayShortsCardView 내에서 Text 사이즈를 frame으로 고정시켜주고 있었어서 그걸 뺐고, 다른 것들 같이 수정했더니 해결되었습니다!!!
[링크 참고](https://github.com/mash-up-kr/SeeYouAgain_iOS/commit/f41b7ed585f6cd1021faefdd4802531552c3f922)
![CleanShot 2023-06-24 at 12 24 20](https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/95578975/49e98027-4e09-4dac-ac40-b57700f7fb28)

2023-06-24 03:36 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
> +  var currentTimeSeconds: Int = 0 // 지금 시간이 몇초를 담고있냐! 17:27:21 => 62841
없습니다.. 꼼꼼히 확인했어야했는데ㅠㅠ public 키워드 모두 삭제했습니다.. 😓

2023-06-24 03:50 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
> +      state.isInEditMode.toggle()
좋습니다!!!! `_toggleEditMode`라는 액션 추가해서 수정했습니다!

2023-06-24 04:39 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
> +        ScrollView {
수정했습니다! 1차 배포후에 더 리팩토링해볼게요!!!

2023-06-24 04:41 UTC, AhnSangHee commented on Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
> +      return Effect(value: ._updateTimer)
요거 1차 배포 이후 수정해보겠습니다!!!

2023-06-24 04:43 UTC, klmyoungyun approved these changes

2023-06-24 04:51 UTC, GREENOVER approved these changes

2023-06-24 04:54 UTC, merged