기능: 키워드 내 뉴스 리스트 화면 구현
mash-up-kr/SeeYouAgain_iOS pull request #67
Opened 2023-06-25 06:38 UTC by AhnSangHee

## Task

[]()

## 참고

2023-06-25 11:46 UTC, GREENOVER requested changes
참고와 문제 사항에 적어주신 내용에 대해서는 피그마에서 같이 얘기 나눠서
해당 부분 수정되고 다시 push되면 고쪽 부분까지해서 같이 보겠습니다~!

2023-06-25 11:46 UTC, GREENOVER commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
> +public struct News: Equatable, Identifiable {
요런 타입들 모델 모듈쪽으로 빼도 좋을듯 합니다🙋🏻
stub 데이터 만들기도 편하고 분리가 잘될거 같아요!

만약 아직 API 연동 전이여서 테스트용으로 두었다면 코멘트 무시해주세요~!

2023-06-25 11:46 UTC, GREENOVER commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
> +          AsyncImage(url: URL(string: imageUrl)) { phase in
AsyncImage로 사용할 예정이시라면 저희 초기에 채택해둔 Nuke 라이브러리 제거 부탁드립니다🙏🏻

2023-06-25 11:46 UTC, GREENOVER commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
> +  ) {
파라미터 하나라 한 라인으로 가도 좋을듯합니다~!

2023-06-25 15:05 UTC, klmyoungyun commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
> +          AsyncImage(url: URL(string: imageUrl)) { phase in
누크사용해쥬ㅓ요이잉잉이잉
<img src="https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/48887389/b5fe7214-4f10-42c6-b843-e0bc96bfd0d6" width="400"/>

2023-06-25 15:10 UTC, AhnSangHee commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
> +          AsyncImage(url: URL(string: imageUrl)) { phase in
Nuke 라이브러리로 사용 변경했습니다~!

2023-06-25 15:13 UTC, AhnSangHee commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
> +public struct News: Equatable, Identifiable {
요거 테스트용이라 API 연동하면서 모두 수정하겠습니다!

2023-06-25 15:21 UTC, klmyoungyun reviewed
고생하셨습니다!!

![](https://r2.jjalbot.com/2023/03/yi83-0udOv.gif)

2023-06-25 15:21 UTC, klmyoungyun commented on Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
> +  var body: some View {
요거도 `fileprivate` 키워드 붙이면 좋을 것 같습니다!

2023-06-25 15:21 UTC, klmyoungyun commented on Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
> +    ),
리듀서 풀백 순서도 State에 나열한 순서대로 하면 어떤가요..!!
<img src="https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/48887389/b64115ce-d3f5-4abd-8582-99f8f7199c74" width="300"/>

2023-06-25 15:23 UTC, AhnSangHee commented on Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
> +    ),
반영완료~_~
![image](https://github.com/mash-up-kr/SeeYouAgain_iOS/assets/95578975/cbf8f27e-03f4-4b18-bd25-0b315e08b246)

2023-06-25 15:25 UTC, klmyoungyun approved these changes

2023-06-26 00:38 UTC, GREENOVER approved these changes
GOOOOOOOD 👍👍

2023-06-26 03:03 UTC, GREENOVER commented
@AhnSangHee 
퀵하게 머지하고 담 스텝으로 넘어가시죠~!

2023-06-26 03:04 UTC, merged